name: "Deploy to Production"
on: "workflow_dispatch"

jobs: 
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      
      - name: "Install Dependencies"
        run: npm install

      - name: "Install PM2"
        run: npm install pm2 -g
      
      - name: "Deploy to Production"
        run: |
          pm2 stop all
          pm2 start src/index.js