name: "Deploy to Production"
on: "workflow_dispatch"

jobs: 
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      
      - name: "Install Dependencies"
        run: npm install

      
      - name: "Deploy to Production"
        run: |
          pm2 restart src/index.js